version: '3.7'

services:
  stack:
    container_name: stack
    hostname: stack
    image: stack:dev
    restart: always
    networks:
      - default
    environment:
      - VIRTUAL_HOST=stack${HOST_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stack${HOST_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: webproxy
